#!/bin/sh
export CLASSPATH=$CLASSPATH:./jgrapht-jdk1.6.jar
javac ./wrapper/*.java
javac ./objects/*.java
javac ./static_classes/*.java
javac ./gui/staff/*.java
javac ./gui/passenger/*.java

echo 
echo java gui/passenger/Passenger
