/*
 * Passenger.java
 *
 * Created on 18-Apr-2013, 14:46:42
 */

/**
 *
 * @author Adam Nogradi
 */
public class Passenger extends javax.swing.JFrame {

   private static Passenger passenger;
   public static JourneyPlanner journeyPlanner;
   public static Timetables timetables;
   public static RealTimeInfo realTimeInfo;
    /** Creates new form Passenger */
    public Passenger() {
        initComponents();
        database.openBusDatabase();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new javax.swing.JPanel();
        planJourneyButton = new javax.swing.JButton();
        timetablesButton = new javax.swing.JButton();
        realTimeButton = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        welcomeLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Passenger Menu");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Passenger Menu"); // NOI18N
        setResizable(false);

        buttonsPanel.setLayout(new java.awt.GridLayout(1, 3));

        planJourneyButton.setText("Plan a journey");
        planJourneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planJourneyButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(planJourneyButton);

        timetablesButton.setText("Timetables");
        timetablesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetablesButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(timetablesButton);

        realTimeButton.setText("Get real-time info");
        realTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realTimeButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(realTimeButton);

        welcomeLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome!");

        welcomeLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        welcomeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel2.setText("Please select an option from the menu below:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomeLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(welcomeLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-443)/2, (screenSize.height-163)/2, 443, 163);
    }// </editor-fold>//GEN-END:initComponents

    private void realTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realTimeButtonActionPerformed
        // TODO add your handling code here:
        displayRealTimeInfo ();
    }//GEN-LAST:event_realTimeButtonActionPerformed

    private void planJourneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planJourneyButtonActionPerformed
        // TODO add your handling code here:
        displayJourneyPlanner ();
    }//GEN-LAST:event_planJourneyButtonActionPerformed

    private void timetablesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timetablesButtonActionPerformed
        // TODO add your handling code here:
        displayTimetables ();
    }//GEN-LAST:event_timetablesButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               passenger = new Passenger();
               passenger.setVisible (true);                
            }
        });
    }

    private void displayJourneyPlanner ()
    {
        journeyPlanner = new JourneyPlanner (this);
        //passenger.setVisible (false);
        passenger.setVisible(false);
        journeyPlanner.setVisible (true);
    }

    private void displayTimetables ()
    {
        timetables = new Timetables ();
        passenger.setVisible (false);
        timetables.setVisible (true);
    }

    private void displayRealTimeInfo ()
    {
        realTimeInfo = new RealTimeInfo ();
        passenger.setVisible (false);
        realTimeInfo.setVisible (true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton planJourneyButton;
    private javax.swing.JButton realTimeButton;
    private javax.swing.JButton timetablesButton;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel welcomeLabel2;
    // End of variables declaration//GEN-END:variables

}
