package gui.passenger;
import objects.*;
import wrapper.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RealTimeInfo.java
 *
 * Created on 22-Apr-2013, 11:53:23
 */

/**
 *
 * @author Adam Nogradi
 */
import java.awt.Color;

public class RealTimeInfo extends javax.swing.JFrame {

    private Passenger passenger;
    private Area[] allAreas = Area.getAllAreas();
    private String[] allAreaNames = new String[allAreas.length];
    private String selectedArea;

    /** Creates new form RealTimeInfo */
    public RealTimeInfo(Passenger pass) {
        passenger = pass;
        for (int i = 0; i < allAreas.length; i++)
        {
            allAreaNames[i] = allAreas[i].getName();
        }
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        stopSelectLabel = new javax.swing.JLabel();
        areaBox = new javax.swing.JComboBox();
        areaLabel = new javax.swing.JLabel();
        stopLabel = new javax.swing.JLabel();
        busStopBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        resultPanel = new javax.swing.JPanel();
        areaScroolPane = new javax.swing.JScrollPane();
        resultTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setText("Back to menu");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 24));
        titleLabel.setText("Get real-time information");

        stopSelectLabel.setText("Select the area and the bus stop:");

        areaBox.setModel(new javax.swing.DefaultComboBoxModel());
        areaBox.addItem("Select...");
        for (int i = 0; i < allAreaNames.length; i++)
        areaBox.addItem(allAreaNames[i]);
        areaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaBoxActionPerformed(evt);
            }
        });

        areaLabel.setFont(new java.awt.Font("DejaVu Sans", 2, 13));
        areaLabel.setText("Area:");

        stopLabel.setFont(new java.awt.Font("DejaVu Sans", 2, 13));
        stopLabel.setText("Bus stop:");

        busStopBox.setModel(new javax.swing.DefaultComboBoxModel());
        busStopBox.addItem("(Select an area...)");

        jButton1.setText("Get Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        resultTextArea.setEnabled (false);
        resultTextArea.setDisabledTextColor (Color.black);
        resultTextArea.setColumns(20);
        resultTextArea.setRows(5);
        resultTextArea.setText("hello");
        areaScroolPane.setViewportView(resultTextArea);

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
            .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(resultPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(areaScroolPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
            .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(resultPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(areaScroolPane, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backButton)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addComponent(stopSelectLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(areaLabel)
                            .addComponent(areaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(busStopBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stopLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(18, 18, 18)
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopSelectLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaLabel)
                            .addComponent(stopLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(busStopBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        resultPanel.setVisible(false);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-831)/2, (screenSize.height-321)/2, 831, 321);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        passenger.setVisible(true);
        dispose();

    }//GEN-LAST:event_backButtonActionPerformed

    private void areaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaBoxActionPerformed
        // TODO add your handling code here:
        // Obtain the selected item from the list
        selectedArea = (String) areaBox.getSelectedItem();

        // If no item is selected, don't display any relevant bus stops
        if (areaBox.getSelectedItem() == "Select...") {
            busStopBox.removeAllItems();
            busStopBox.addItem("(Select an area...)");
        }

        // Else display the bus stops of the selected area
        else
        {
            Area area = new Area(selectedArea);
            BusStop[] busStopsInArea = area.getUniqueStops();

            busStopBox.removeAllItems();
            //busStopsInArea = BusStopInfo.getBusStopsInArea(BusStopInfo.findAreaByName(selectedArea));


            if (busStopsInArea == null)
                busStopBox.addItem("(No stops in this area)");
            else
            {
                String[] busStopNamesInArea = new String[busStopsInArea.length];
                //System.out.println(busStopNamesInArea.length);
                for (int i = 0; i < busStopNamesInArea.length; i++)
                {
                //int stopID = busStopsInArea[i];
                //System.out.println(stopID);
                busStopNamesInArea[i] = busStopsInArea[i].getName();
                busStopBox.addItem(busStopNamesInArea[i]);
                }
            }
        }
    }//GEN-LAST:event_areaBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resultPanel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox areaBox;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JScrollPane areaScroolPane;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox busStopBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JTextArea resultTextArea;
    private javax.swing.JLabel stopLabel;
    private javax.swing.JLabel stopSelectLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
